-- 分享链接表
CREATE TABLE IF NOT EXISTS share_links (
    id INT PRIMARY KEY AUTO_INCREMENT,
    bill_id INT NOT NULL,
    token VARCHAR(32) NOT NULL UNIQUE,
    expire_at DATETIME DEFAULT NULL,
    is_active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE CASCADE
);
